server:
  port: 1996
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hd?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    prefix=classpath: /templates/
  mvc:
    static-path-pattern: /**
mybatis:
  mapper-locations: mapper/*.xml